// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  var $, $async, $watch, CND, H, PD, VNR, assign, badge, debug, declare, echo, first, help, info, isa, jr, last, rpr, select, size_of, stamp, type_of, types, urge, validate, warn, whisper;

  //###########################################################################################################
  H = require('./helpers');

  CND = require('cnd');

  rpr = CND.rpr;

  badge = H.badge_from_filename(__filename);

  debug = CND.get_logger('debug', badge);

  warn = CND.get_logger('warn', badge);

  info = CND.get_logger('info', badge);

  urge = CND.get_logger('urge', badge);

  help = CND.get_logger('help', badge);

  whisper = CND.get_logger('whisper', badge);

  echo = CND.echo.bind(CND);

  ({jr, assign} = CND);

  //...........................................................................................................
  require('./exception-handler');

  first = Symbol('first');

  last = Symbol('last');

  VNR = require('./vnr');

  //...........................................................................................................
  PD = require('pipedreams');

  ({$, $watch, $async, select, stamp} = PD.export());

  //...........................................................................................................
  types = require('./types');

  ({isa, validate, declare, size_of, type_of} = types);

  //-----------------------------------------------------------------------------------------------------------
  this.$ignore = function(S) {
    var within_ignore;
    within_ignore = false;
    return $((d, send) => {
      if (!select(d, '^line')) {
        return send(d);
      }
      if (d.text === '<ignore>') {
        within_ignore = true;
        return send(stamp(d, {
          dest: 'ignore',
          ref: 'ign'
        }));
      } else if (d.text === '</ignore>') {
        within_ignore = false;
        return send(stamp(d, {
          dest: 'ignore',
          ref: 'ign'
        }));
      } else if (within_ignore) {
        return send(stamp(d, {
          dest: 'ignore',
          ref: 'ign'
        }));
      } else {
        return send(d);
      }
    });
    return null;
  };

  //===========================================================================================================

  //-----------------------------------------------------------------------------------------------------------
  this.$transform = function(S) {
    var pipeline;
    pipeline = [];
    pipeline.push(this.$ignore(S));
    return PD.pull(...pipeline);
  };

}).call(this);

//# sourceMappingURL=006-ignore.js.map
