// Generated by CoffeeScript 2.4.1
(function() {
  'use strict';
  var $, $async, $watch, CND, DM, H, MIRAGE, PD, VNR, assign, badge, cwd_abspath, cwd_relpath, debug, declare, echo, first, first_of, help, here_abspath, info, isa, jr, last, last_of, project_abspath, rpr, select, size_of, stamp, type_of, urge, validate, warn, whisper;

  //###########################################################################################################
  CND = require('cnd');

  rpr = CND.rpr;

  badge = 'DATAMILL/MAIN';

  debug = CND.get_logger('debug', badge);

  warn = CND.get_logger('warn', badge);

  info = CND.get_logger('info', badge);

  urge = CND.get_logger('urge', badge);

  help = CND.get_logger('help', badge);

  whisper = CND.get_logger('whisper', badge);

  echo = CND.echo.bind(CND);

  ({jr, assign} = CND);

  //...........................................................................................................
  require('./exception-handler');

  first = Symbol('first');

  last = Symbol('last');

  MIRAGE = require('mkts-mirage');

  VNR = require('./vnr');

  //...........................................................................................................
  PD = require('pipedreams');

  ({$, $watch, $async, select, stamp} = PD);

  //...........................................................................................................
  this.types = require('./types');

  ({isa, validate, declare, first_of, last_of, size_of, type_of} = this.types);

  //...........................................................................................................
  H = require('./helpers');

  ({cwd_abspath, cwd_relpath, here_abspath, project_abspath} = H);

  //...........................................................................................................
  DM = require('..');

  //-----------------------------------------------------------------------------------------------------------
  this.$decorations = function(S) {
    return $({first, last}, (d, send) => {
      if (d === first) {
        send(H.fresh_datom('^html', {
          text: '<html><body>',
          ref: 'rdh/deco-1',
          $vnr: [-2e308]
        }));
      }
      if (d === last) {
        send(H.fresh_datom('^html', {
          text: '</body></html>',
          ref: 'rdh/deco-2',
          $vnr: [2e308]
        }));
      } else {
        send(d);
      }
      return null;
    });
  };

  // #-----------------------------------------------------------------------------------------------------------
  // @$p = ( S ) -> $ ( d, send ) =>
  //   if select d, '<p'
  //     $vnr = VNR.deepen d.$vnr
  //     send H.fresh_datom '^html', { text: '<p>', ref: 'rdh/p-1', $vnr, }
  //     send d
  //   else if select d, '>p'
  //     $vnr = VNR.deepen d.$vnr
  //     send H.fresh_datom '^html', { text: '</p>', ref: 'rdh/p-2', $vnr, }
  //     send d
  //   else
  //     send d
  //   return null

  //-----------------------------------------------------------------------------------------------------------
  this.$p = function(S) {
    return PD.lookaround($((d3, send) => {
      var $vnr, d, nxt, prv, text;
      [prv, d, nxt] = d3;
      if (!select(d, '^mktscript')) {
        return null;
      }
      text = d.text;
      if (select(prv, '<p')) {
        text = `<p>${text}`;
      }
      if (select(nxt, '>p')) {
        text = `${text}</p>`;
      }
      $vnr = VNR.deepen(d.$vnr);
      send(H.fresh_datom('^html', {
        text: text,
        ref: 'rdh/p',
        $vnr
      }));
      send(d);
      return null;
    }));
  };

  // #-----------------------------------------------------------------------------------------------------------
  // @$mktscript = ( S ) -> $ ( d, send ) =>
  //   if select d, '^mktscript'
  //     $vnr = VNR.deepen d.$vnr
  //     send H.fresh_datom '^html', { text: d.text, ref: 'rdh/mkts-1', $vnr, }
  //     send d
  //   else
  //     send d
  //   return null

  //-----------------------------------------------------------------------------------------------------------
  this.$blank = function(S) {
    return $((d, send) => {
      var $vnr, _, i, ref, ref1;
      if (!select(d, '^blank')) {
        return send(d);
      }
      $vnr = VNR.deepen(d.$vnr);
      for (_ = i = 1, ref = (ref1 = d.linecount) != null ? ref1 : 0; i <= ref; _ = i += +1) {
        $vnr = VNR.advance($vnr);
        send(H.fresh_datom('^html', {
          text: '',
          ref: 'rdh/mkts-1',
          $vnr
        }));
      }
      return send(d);
    });
  };

  //===========================================================================================================

  //-----------------------------------------------------------------------------------------------------------
  this.render = function(S) {
    return new Promise((resolve, reject) => {
      var pipeline;
      H.register_key(S, '^html', {
        is_block: false
      });
      pipeline = [];
      // pipeline.push @$line      S
      // pipeline.push @$decorations S
      pipeline.push(this.$p(S));
      // pipeline.push @$mktscript   S
      pipeline.push(this.$blank(S));
      DM.run_phase(S, PD.pull(...pipeline));
      //.........................................................................................................
      // dbr = S.mirage.dbr
      // dbw = S.mirage.dbw
      // { to_width
      //   width_of }              = require 'to-width'
      // dbw.create_view_rows_mktscript_and_block_tags()
      // for row from dbr.$.query "select * from rows_mktscript_and_block_tags;"
      //   d = H.datom_from_row S, row
      //   urge 'µ10922', jr d
      // for row from dbr.texts_preceded_by_block_keys()
      //   $vnr    = VNR.deepen JSON.parse row.vnr
      //   text    = "#{row.prv_key}>#{row.text}"
      //   d       = H.fresh_datom '^html', { text, $vnr, ref: 'rdh/x1', }
      //   debug 'µ33431', jr d
      //   dbw.insert H.row_from_datom S, d
      // for row from dbr.texts_followed_by_block_keys()
      //   urge 'µ33431', jr row
      //   $vnr    = VNR.deepen JSON.parse row.vnr
      //   text    = "#{row.text}</#{row.nxt_key[ 1 .. ]}>"
      //   d       = H.fresh_datom '^html', { text, $vnr, ref: 'rdh/x2', }
      //   urge 'µ33431', jr d
      //   dbw.insert H.row_from_datom S, d
      //.........................................................................................................
      return resolve();
    });
  };

}).call(this);

//# sourceMappingURL=render-as-html.js.map
