// Generated by CoffeeScript 2.4.1
(function() {
  'use strict';
  var CND, Intertype, alert, badge, debug, help, info, intertype, jr, rpr, urge, warn, whisper;

  //###########################################################################################################
  CND = require('cnd');

  rpr = CND.rpr;

  badge = 'MKTS-PARSER/TYPES';

  debug = CND.get_logger('debug', badge);

  alert = CND.get_logger('alert', badge);

  whisper = CND.get_logger('whisper', badge);

  warn = CND.get_logger('warn', badge);

  help = CND.get_logger('help', badge);

  urge = CND.get_logger('urge', badge);

  info = CND.get_logger('info', badge);

  jr = JSON.stringify;

  Intertype = (require('intertype')).Intertype;

  intertype = new Intertype(module.exports);

  //-----------------------------------------------------------------------------------------------------------
  this.declare('datamill_phase_repeat', function(x) {
    if (x == null) {
      return true;
    }
    if (this.isa.boolean(x)) {
      return true;
    }
    return this.isa.function(x);
  });

  //-----------------------------------------------------------------------------------------------------------
  this.declare('datamill_region', function(x) {
    return {
      tests: {
        "x is a ?object": function(x) {
          return (x == null) || this.isa.object(x);
        },
        "x.start_vnr is a vnr": function(x) {
          return isa.vnr(x.start_vnr);
        },
        "x.stop_vnr is a vnr": function(x) {
          return isa.vnr(x.stop_vnr);
        }
      }
    };
  });

  //-----------------------------------------------------------------------------------------------------------
  this.declare('datamill_register_key_settings', function(x) {
    return {
      tests: {
        "x is a object": function(x) {
          return this.isa.object(x);
        },
        "x.is_block is a boolean": function(x) {
          return this.isa.boolean(x.is_block);
        },
        "x.has_paragraphs is a ?boolean": function(x) {
          return (x.has_paragraphs == null) || this.isa.boolean(x.has_paragraphs);
        }
      }
    };
  });

  // tests:
//   "optional x is function or boolean":
//     "x is a object":                          ( x ) -> @isa.object          x
//     "x has key 'key'":                        ( x ) -> @has_key             x, 'key'
//     "x has key 'vlnr_txt'":                   ( x ) -> @has_key             x, 'vlnr_txt'
//     "x has key 'value'":                      ( x ) -> @has_key             x, 'value'
//     "x.key is a nonempty text":               ( x ) -> @isa.nonempty_text   x.key
//     "x.vlnr_txt is a nonempty text":          ( x ) -> @isa.nonempty_text   x.vlnr_txt
//     "x.vlnr_txt starts, ends with '[]'":      ( x ) -> ( x.vlnr_txt.match /^\[.*\]$/ )?
//     "x.vlnr_txt is a JSON array of integers": ( x ) ->
//       # debug 'µ55589', x
//       ( @isa.list ( lst = JSON.parse x.vlnr_txt ) ) and \
//       ( lst.every ( xx ) => ( @isa.integer xx ) and ( @isa.positive xx ) )

}).call(this);

//# sourceMappingURL=types.js.map
