// Generated by CoffeeScript 2.5.1
(function() {
  'use strict';
  var inspect;

  //###########################################################################################################
  ({inspect} = require('util'));

  //-----------------------------------------------------------------------------------------------------------
  this.xrpr = function(x) {
    return inspect(x, {
      colors: true,
      breakLength: 2e308,
      maxArrayLength: 2e308,
      depth: 2e308
    });
  };

  //-----------------------------------------------------------------------------------------------------------
  this.xr = function(x) {
    return inspect(x, {
      colors: false,
      breakLength: 2e308,
      maxArrayLength: 2e308,
      depth: 2e308
    });
  };

}).call(this);

//# sourceMappingURL=xr.js.map
